version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:!Nuvola3@db:5432/frantoio?schema=public
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!Nuvola3
      - POSTGRES_DB=frantoio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
